/file/set-tui-version "19.4"
(cx-gui-do cx-activate-item "Ribbon*Frame1*Frame5(Solution)*Table1*Table3(Activities)*PushButton2(Create)")
(cx-gui-do cx-activate-item "MenuBar*PopupMenuCreate*Execute Commands...")
(cx-gui-do cx-set-integer-entry "Execute Commands*IntegerEntry1(Defined Commands)" 1)
(cx-gui-do cx-activate-item "Execute Commands*IntegerEntry1(Defined Commands)")
(cx-gui-do cx-set-toggle-button2 "Execute Commands*Table2*CheckButton6" #t)
(cx-gui-do cx-activate-item "Execute Commands*Table2*CheckButton6")
(cx-gui-do cx-set-text-entry "Execute Commands*Table2*TextEntry11" "/file/read-journal output_residual.jou")
(cx-gui-do cx-activate-item "Execute Commands*PanelButtons*PushButton1(OK)")
(cx-gui-do cx-set-list-tree-selections "NavigationPane*List_Tree1" (list "Solution|Run Calculation"))
(cx-gui-do cx-set-list-tree-selections "NavigationPane*List_Tree1" (list "Solution|Run Calculation"))
(cx-gui-do cx-activate-item "NavigationPane*List_Tree1")
(cx-gui-do cx-set-list-tree-selections "NavigationPane*List_Tree1" (list "Solution|Run Calculation"))
(cx-gui-do cx-set-integer-entry "Run Calculation*Table1*Table7*IntegerEntry2(Number of Time Steps)" 80)
(cx-gui-do cx-activate-item "Run Calculation*Table1*Table7*IntegerEntry2(Number of Time Steps)")
(cx-gui-do cx-activate-item "Run Calculation*Table1*PushButton22(Calculate)")
(cx-gui-do cx-activate-item "Settings have changed!*PanelButtons*PushButton1(OK)")